# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dm-validations-i18n}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Masaki KOMAGATA"]
  s.date = %q{2010-10-03}
  s.description = %q{Localize error messages in dm-validations.}
  s.email = %q{komagata@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "dm-validations-i18n.gemspec",
     "lib/dm-validations-i18n.rb",
     "locale/en.yml",
     "locale/ja.yml",
     "test/helper.rb",
     "test/test_dm-validations-i18n.rb"
  ]
  s.homepage = %q{http://github.com/komagata/dm-validations-i18n}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{localize dm-validations}
  s.test_files = [
    "test/helper.rb",
     "test/test_dm-validations-i18n.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<dm-validations>, [">= 1.0.2"])
      s.add_development_dependency(%q<shoulda>, [">= 2.11.3"])
    else
      s.add_dependency(%q<dm-validations>, [">= 1.0.2"])
      s.add_dependency(%q<shoulda>, [">= 2.11.3"])
    end
  else
    s.add_dependency(%q<dm-validations>, [">= 1.0.2"])
    s.add_dependency(%q<shoulda>, [">= 2.11.3"])
  end
end

